from enum import Enum


class ResponseCode(str, Enum):
  """HTTP 응답 코드 Enum (자동완성 지원)"""

  # 성공 (2xx)
  OK = 'OK'
  CREATED = 'CREATED'
  ACCEPTED = 'ACCEPTED'
  NO_CONTENT = 'NO_CONTENT'

  # 클라이언트 에러 (4xx)
  BAD_REQUEST = 'BAD_REQUEST'
  UNAUTHORIZED = 'UNAUTHORIZED'
  FORBIDDEN = 'FORBIDDEN'
  NOT_FOUND = 'NOT_FOUND'
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
  CONFLICT = 'CONFLICT'
  VALIDATION_ERROR = 'VALIDATION_ERROR'
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY'

  # 서버 에러 (5xx)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
  BAD_GATEWAY = 'BAD_GATEWAY'
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
